source "https://rubygems.org"

gem "jekyll"
gem "bulma-clean-theme"
gem "jekyll-sitemap"
gem "jekyll-paginate"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "kramdown-parser-gfm"
gem "jekyll-redirect-from"
